export const ERROR_CODES = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  TELEGRAM_AUTH_FAILED: 'TELEGRAM_AUTH_FAILED',
  USER_BANNED: 'USER_BANNED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Inventory & Stock
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  DUPLICATE_STOCK_HASH: 'DUPLICATE_STOCK_HASH',
  STOCK_LOCKED: 'STOCK_LOCKED',

  // Order & Cart
  INVALID_ORDER_STATE: 'INVALID_ORDER_STATE',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  PRICE_MISMATCH: 'PRICE_MISMATCH',
  MIN_ORDER_AMOUNT: 'MIN_ORDER_AMOUNT',
  MAX_ORDER_AMOUNT: 'MAX_ORDER_AMOUNT',

  // Payment
  PAYMENT_CREATION_FAILED: 'PAYMENT_CREATION_FAILED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  AMOUNT_MISMATCH: 'AMOUNT_MISMATCH',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',

  // Wallet
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',

  // Coupon
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',

  // General Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
};
