export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
  USER: 'USER'
};

export const PERMISSIONS = {
  MANAGE_PRODUCTS: ['SUPER_ADMIN', 'ADMIN'],
  MANAGE_STOCK: ['SUPER_ADMIN', 'ADMIN'],
  MANAGE_ORDERS: ['SUPER_ADMIN', 'ADMIN', 'STAFF'],
  MANAGE_USERS: ['SUPER_ADMIN', 'ADMIN'],
  MANAGE_COUPONS: ['SUPER_ADMIN', 'ADMIN'],
  MANAGE_SETTINGS: ['SUPER_ADMIN'],
  VIEW_LOGS: ['SUPER_ADMIN', 'ADMIN']
};
